.DEFAULT_GOAL := help

.PHONY: help
help:: ## Print this help message
	@printf 'Usage: make <command>\n\nCommands:\n'
	@grep -hE '^[a-zA-Z0-9_-]+:+(.*?##.*| [\$$a-zA-Z0-9].*)?$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":+([^#]*)(##)?"}; {printf "    \033[36m%-30s\033[0m %s\n", $$1, $$2}'

debug::
	$(MAKE) --version
