#!/usr/bin/env bash
alias gb='g build'
alias gcb='g clean build'
alias gt='g test'
alias g_clean_build='g clean build'
alias g_comp_cache='__gradle-completion-init'
alias g_quiet='g --quiet'
alias g_quietplain='g --quiet --console plain'

alias g_rv='g_refresh_versions'
alias g_rvc='g_refresh_versions_cleanup'
alias g_rvm='g_refresh_versions_migrate'
alias grv='g_refresh_versions'
alias grvc='g_refresh_versions_cleanup'
alias grvm='g_refresh_versions_migrate'
